version: '3.2'
services:
  # category-service:
  #   build:
  #     context: ./
  #     dockerfile: TODO
  #   ports:
  #     - "8081:8080"
  #   depends_on:
  #     - db-image-product
  #   networks:
  #     - microservices

  # db-image-category:
  #   build:
  #     context: ./
  #     dockerfile: microservices/category-service/docker/DockerfileMySQLCategory
  #   volumes:
  #     - "./.data/category:/var/lib/mysql"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     local_dev_net_1:
  #       aliases:
  #         - db-image-category

  product-db:
    hostname: product-db
    build:
      context: microservices/product-service
      dockerfile: docker/DockerfileMySQLProduct
    volumes:
      - "./.data/product:/var/lib/mysql"
    ports:
      - "3307:3306"
    networks:
      - microservices

  product-service:
    build:
      context: microservices/product-service
      dockerfile: docker/DockerProductMicroservice
    ports:
      - "8081:8080"
    depends_on:
      - product-db
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
