version: '3.2'
services:
  category-db:
    hostname: category-db
    build:
      context: ./microservices/category-service
      dockerfile: docker/CategoryDatabase
    volumes:
      - "./.data/category:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    networks:
      backend:
        aliases:
          - category-db

  category-service:
    hostname: category-service
    build:
      context: ./microservices/category-service
      dockerfile: docker/CategoryService
    ports:
      - "8080:8080"
      - "5006:5006"
    depends_on:
      - category-db
    networks:
      - backend
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006

  product-db:
    hostname: product-db
    build:
      context: ./microservices/product-service
      dockerfile: docker/ProductDatabase
    volumes:
      - "./.data/product:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    networks:
      backend:
        aliases:
          - product-db

  product-service:
    hostname: product-service
    build:
      context: ./microservices/product-service
      dockerfile: docker/ProductService
    ports:
      - "8081:8080"
      - "5005:5005"
    depends_on:
      - product-db
    networks:
      - backend
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

networks:
  backend:
    driver: bridge
