version: '3.2'
services:
  db-image-category:
    build:
      context: ./
      dockerfile: microservices/category-service/docker/DockerfileMySQLCategory
    volumes:
      - "./.data/category:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
    ports:
      - "3306:3306"
    networks:
      local_dev_net_1:
        aliases:
          - db-image-category

  db-image-product:
    build:
      context: ./
      dockerfile: microservices/product-service/docker/DockerfileMySQLProduct
    volumes:
      - "./.data/product:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
    ports:
      - "3307:3306"
    networks:
      local_dev_net_2:
            aliases:
                - db-image-product

networks:
  local_dev_net_1:
  local_dev_net_2:
    driver: bridge
