version: '3.2'
services:
  db-image-product:
    build:
      context: ./
      dockerfile: docker/DockerfileMySQLProduct
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
    ports:
      - "3307:3306"
    networks:
      local_dev_net:
        aliases:
          - db-image-product

networks:
  local_dev_net:
    driver: bridge
